export const SampleGameWallTextures = [
  { index: "officewall", image: "OfficeWall.png" },
  { index: "panel", image: "Panel.png" },
  { index: "hedge", image: "Hedge.png" },
  { index: "door", image: "OfficeDoor.png" },
  { index: "elevator", image: "Portal.png" },
  { index: "bluedoor", image: "OfficeDoorBlue.png" },
  { index: "field", image: "Field.png" },
];

export const GAME_WALL_MAP = {
  0: {
    name: "empty",
    textures: [{ 0: "empty" }],
    height: 0,
    collide: false,
    miniMapColor: "#0c1220",
  },
  1: {
    name: "officewall",
    textures: [{ 0: "officewall" }],
    height: 1,
    collide: true,
    miniMapColor: "#ECDE60",
  },
  2: {
    name: "panel",
    textures: [{ 0: "panel" }],
    height: 1,
    collide: true,
    miniMapColor: "#707a88",
  },
  3: {
    name: "hedge",
    textures: [{ 0: "hedge" }],
    height: 1,
    collide: true,
    miniMapColor: "#00e676",
  },
  4: {
    name: "door",
    textures: [{ 0: "door" }],
    height: 1,
    collide: true,
    miniMapColor: "#996633",
  },
  5: {
    name: "elevator",
    textures: [{ 0: "elevator" }],
    height: 1,
    collide: false,
    miniMapColor: "#FFE300",
  },
  6: {
    name: "bluedoor",
    textures: [{ 0: "bluedoor" }],
    height: 1,
    collide: false,
    miniMapColor: "#3561ff",
  },
  7: {
    name: "field",
    textures: [{ 0: "field" }],
    height: 1,
    collide: true,
    miniMapColor: "#00FFFF",
  },
  9: {
    name: "bluedoor",
    textures: [{ 0: "bluedoor", 1: "officewall", 2: "officewall" }],
    height: 3,
    collide: false,
    miniMapColor: "#3561ff",
  },
  8: {
    name: "tallwall",
    textures: [{ 0: "officewall", 1: "officewall", 2: "officewall" }],
    height: 3,
    collide: true,
    miniMapColor: "#ECDE90",
  },
};
